server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/my-site
    username: my-site
    password: my-site
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgresPlusDialect
    show-sql: true